[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/fonts/*"
  to = "/fonts/:splat"
  status = 200
